#!/bin/sh
mkdir -p "$HOME/.config/sway" 2>/dev/null

HOSTNAME=$(cat /etc/hostname)
if [ -f "$PWD/config.$HOSTNAME" ]; then
  ln -fs "$PWD/config.$HOSTNAME" "$HOME/.config/sway/config"
else
  echo "Warning: no sway config for hostname '$HOSTNAME'" >&2
fi
