#!/bin/sh
set -e

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.bash_profile" "$HOME/.bash_profile"

for i in foot git starship sway tmux; do
  cd $i && ./setup
  cd -
done
