#!/bin/sh
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/gh
mkdir -p "$config_dir"
ln -fs "$repo_dir/config.yml" "$config_dir/config.yml"
