#!/bin/sh
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/waybar
hostname=$(cat /etc/hostname)
mkdir -p "$config_dir"
if [ -f "$repo_dir/config.$hostname" ]; then
  ln -fs "$repo_dir/config.$hostname" "$config_dir/config"
else
  echo "Warning: no waybar config for hostname '$hostname'" >&2
  exit 1
fi

if [ -f "$repo_dir/style.$hostname" ]; then
  ln -fs "$repo_dir/style.$hostname" "$config_dir/style.css"
else
  echo "Warning: no waybar style for hostname '$hostname'" >&2
  exit 1
fi
