#!/bin/sh
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/nvim
mkdir -p "$config_dir"
for item in init.lua lazy-lock.json lazyvim.json lua stylua.toml .neoconf.json .gitignore LICENSE README.md; do
  if [ -e "$repo_dir/$item" ]; then
    rm -rf "${config_dir:?}/$item"
    ln -fns "$repo_dir/$item" "$config_dir/$item"
  fi
done
