#!/bin/sh
mkdir -p "$HOME/.config/nvim"
for item in init.lua lazy-lock.json lua; do
  [ -e "$HOME/.config/nvim/$item" ] && rm -rf "$HOME/.config/nvim/$item"
  ln -s "$PWD/$item" "$HOME/.config/nvim/$item"
done
