#!/bin/sh
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/tmux
mkdir -p "$config_dir"
ln -fs "$repo_dir/tmux.conf" "$config_dir/tmux.conf"
