# Disable status bar (prefer index)
set -g status off

# Enable mouse support
set -g mouse on

# For vi/tmux d/y buffer sync
set -g focus-events on

# vi keys for copy mode
setw -g mode-keys vi

# vi keys for command status
set -g status-keys vi

# Use vi keys to navigate panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Use vi keys to resize panes
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# Set default terminal and 256 colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",foot:Tc"
