# Disable status bar
set -g status off

# Enable mouse support
set -g mouse on

# Set fish as default tmux shell
set-option -g default-shell "/usr/bin/fish"

# For vim/tmux d/y buffer sync
set -g focus-events

# Use vim keys for copy mode
setw -g mode-keys vi

# Use vim keys for command status
set -g status-keys vi

# Address vim mode switching delay
set -s escape-time 0

# Use vim keys to navigate panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Renumber windows in numerical order
set -g renumber-windows on

# True color support
set -g default-terminal "$TERM"
set -g terminal-overrides ",$TERM:Tc"
