#!/bin/sh
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/fish
mkdir -p "$config_dir/functions"
ln -fs "$repo_dir/config.fish" "$config_dir/config.fish"

for file in "$repo_dir/functions/"*; do
  [ -f "$file" ] || continue
  ln -fs "$file" "$config_dir/functions/$(basename "$file")"
done
