[main]
font=JetBrainsMono Nerd Font:size=11:style=Regular
dpi-aware=yes
pad=6x6

# Gruvbox Material Dark Medium
[colors-dark]
background=282828 # black
foreground=d4be98 # white
regular0=282828   # black
regular1=ea6962   # red
regular2=a9b665   # green
regular3=d8a657   # yellow
regular4=7daea3   # blue
regular5=d3869b   # magenta
regular6=89b482   # cyan
regular7=d4be98   # white
bright0=282828    # black
bright1=ea6962    # red
bright2=a9b665    # green
bright3=d8a657    # yellow
bright4=7daea3    # blue
bright5=d3869b    # magenta
bright6=89b482    # cyan
bright7=d4be98    # white
