#!/bin/sh
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/foot
mkdir -p "$config_dir"
ln -fs "$repo_dir/foot.ini" "$config_dir/foot.ini"
